<center>
<h2><b>Muhammad Abdullah</b></h2>
<h2><b>F22607010</b></h2>
</center>


In [16]:
import numpy  as np

arr = np.array([[30, 2, 3],
                [4, 15, 6],
                [7, 8, 9]])

max_indices = np.argmax(arr, axis=1)
min_indices = np.argmin(arr, axis=1)

print("Indices of maximum values along axis 1:", max_indices)
print("Indices of minimum values along axis 1:", min_indices)


Indices of maximum values along axis 1: [0 1 2]
Indices of minimum values along axis 1: [1 0 0]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

comparison = np.array_equal(arr1, arr2)

print("Arrays are equal:", comparison)


Arrays are equal: True


In [17]:

first_names = np.array(['Abdullah', 'Zohaib', 'Moeez'])
last_names = np.array(['Zafar', 'Afzaal', 'Ahmad', ])


sorted_indices = np.lexsort((first_names, last_names))
print(sorted_indices)

sorted_first_names = first_names[sorted_indices]
sorted_last_names = last_names[sorted_indices]

print(sorted_first_names)
print(sorted_last_names)

[1 2 0]
['Zohaib' 'Moeez' 'Abdullah']
['Afzaal' 'Ahmad' 'Zafar']


In [11]:

diagnoal_Val = [4, 5, 6, 8]

result_array = np.diag(diagnoal_Val)

print(result_array)


[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [9]:

def filter_even_elements(arr):
    return arr[arr % 2 == 0]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filtered_arr = filter_even_elements(arr)
print(filtered_arr)

[ 2  4  6  8 10]


In [13]:

array = np.arange(-10, 11)
print("Orginal Array = ",array)

positive_array = array[array > 0]
print(positive_array)


Orginal Array =  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]


In [14]:

array_3d = np.arange(1, 28).reshape((3, 3, 3))

diagonals = np.array([np.diag(array_3d[i]) for i in range(array_3d.shape[0])])


print("3-D array:")
print(array_3d)

print("\nDiagonals from each 2-D slice:")
print(diagonals)


3-D array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Diagonals from each 2-D slice:
[[ 1  5  9]
 [10 14 18]
 [19 23 27]]
